//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMK_Assistant.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.125,Mini;0.25,X-Small;0.375,Small;0.5,Medium;0.625,Large;0.75,X-Large;1,Full")]
        public string OverlaySizes {
            get {
                return ((string)(this["OverlaySizes"]));
            }
            set {
                this["OverlaySizes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double OverlayOpacityStep {
            get {
                return ((double)(this["OverlayOpacityStep"]));
            }
            set {
                this["OverlayOpacityStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Top Left,Left,10,Top,10;Top,Center,0,Top,10;Top Right,Right,10,Top,10;Right,Right" +
            ",10,Middle,0;Bottom Right,Right,10,Bottom,10;Bottom,Center,10,Bottom,10;Bottom L" +
            "eft,Left,10,Bottom,10;Left,Left,10,Middle,10;Center,Center,0,Middle,0")]
        public string OverlayPositions {
            get {
                return ((string)(this["OverlayPositions"]));
            }
            set {
                this["OverlayPositions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonitorDefault {
            get {
                return ((bool)(this["MonitorDefault"]));
            }
            set {
                this["MonitorDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int LayerMax {
            get {
                return ((int)(this["LayerMax"]));
            }
            set {
                this["LayerMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources\\\\Legends")]
        public string LegendsPath {
            get {
                return ((string)(this["LegendsPath"]));
            }
            set {
                this["LegendsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double LegendMargin {
            get {
                return ((double)(this["LegendMargin"]));
            }
            set {
                this["LegendMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public double BaseUnit {
            get {
                return ((double)(this["BaseUnit"]));
            }
            set {
                this["BaseUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double DefaultSpacing {
            get {
                return ((double)(this["DefaultSpacing"]));
            }
            set {
                this["DefaultSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double BorderShadeFactor {
            get {
                return ((double)(this["BorderShadeFactor"]));
            }
            set {
                this["BorderShadeFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Both")]
        public string DefaultOverlayDisplay {
            get {
                return ((string)(this["DefaultOverlayDisplay"]));
            }
            set {
                this["DefaultOverlayDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Small")]
        public string DefaultOverlaySize {
            get {
                return ((string)(this["DefaultOverlaySize"]));
            }
            set {
                this["DefaultOverlaySize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bottom Right")]
        public string DefaultOverlayPosition {
            get {
                return ((string)(this["DefaultOverlayPosition"]));
            }
            set {
                this["DefaultOverlayPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double DefaultOverlayOpacity {
            get {
                return ((double)(this["DefaultOverlayOpacity"]));
            }
            set {
                this["DefaultOverlayOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources\\\\Indicators")]
        public string IndicatorShapePath {
            get {
                return ((string)(this["IndicatorShapePath"]));
            }
            set {
                this["IndicatorShapePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources\\\\Keyboards")]
        public string KeyboardPath {
            get {
                return ((string)(this["KeyboardPath"]));
            }
            set {
                this["KeyboardPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double KeyBorderGap {
            get {
                return ((double)(this["KeyBorderGap"]));
            }
            set {
                this["KeyBorderGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string QMKDisplayOpacityDown {
            get {
                return ((string)(this["QMKDisplayOpacityDown"]));
            }
            set {
                this["QMKDisplayOpacityDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public string QMKDisplayOpacityUp {
            get {
                return ((string)(this["QMKDisplayOpacityUp"]));
            }
            set {
                this["QMKDisplayOpacityUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public string QMKDisplayTypeDown {
            get {
                return ((string)(this["QMKDisplayTypeDown"]));
            }
            set {
                this["QMKDisplayTypeDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public string QMKDisplayTypeUp {
            get {
                return ((string)(this["QMKDisplayTypeUp"]));
            }
            set {
                this["QMKDisplayTypeUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public string QMKDisplaySizeDown {
            get {
                return ((string)(this["QMKDisplaySizeDown"]));
            }
            set {
                this["QMKDisplaySizeDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string QMKDisplaySizeUp {
            get {
                return ((string)(this["QMKDisplaySizeUp"]));
            }
            set {
                this["QMKDisplaySizeUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26")]
        public string QMKDisplayPositionDown {
            get {
                return ((string)(this["QMKDisplayPositionDown"]));
            }
            set {
                this["QMKDisplayPositionDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public string QMKDisplayPositionUp {
            get {
                return ((string)(this["QMKDisplayPositionUp"]));
            }
            set {
                this["QMKDisplayPositionUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2C")]
        public string QMKKeyboardDown {
            get {
                return ((string)(this["QMKKeyboardDown"]));
            }
            set {
                this["QMKKeyboardDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2D")]
        public string QMKKeyboardUp {
            get {
                return ((string)(this["QMKKeyboardUp"]));
            }
            set {
                this["QMKKeyboardUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2B")]
        public string QMKMonitor {
            get {
                return ((string)(this["QMKMonitor"]));
            }
            set {
                this["QMKMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2A")]
        public string QMKDisplaySettingsSave {
            get {
                return ((string)(this["QMKDisplaySettingsSave"]));
            }
            set {
                this["QMKDisplaySettingsSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28")]
        public string QMKSymbolHelp {
            get {
                return ((string)(this["QMKSymbolHelp"]));
            }
            set {
                this["QMKSymbolHelp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29")]
        public string QMKMacroHelp {
            get {
                return ((string)(this["QMKMacroHelp"]));
            }
            set {
                this["QMKMacroHelp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int UpDownDefaultDecimal {
            get {
                return ((int)(this["UpDownDefaultDecimal"]));
            }
            set {
                this["UpDownDefaultDecimal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpDownForceIncrements {
            get {
                return ((bool)(this["UpDownForceIncrements"]));
            }
            set {
                this["UpDownForceIncrements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string DefaultQMKPrefix {
            get {
                return ((string)(this["DefaultQMKPrefix"]));
            }
            set {
                this["DefaultQMKPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public string DefaultQMKSuffix {
            get {
                return ((string)(this["DefaultQMKSuffix"]));
            }
            set {
                this["DefaultQMKSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L")]
        public string DefaultQMKLayer {
            get {
                return ((string)(this["DefaultQMKLayer"]));
            }
            set {
                this["DefaultQMKLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K")]
        public string DefaultQMKKeystroke {
            get {
                return ((string)(this["DefaultQMKKeystroke"]));
            }
            set {
                this["DefaultQMKKeystroke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public string DefaultQMKMacro {
            get {
                return ((string)(this["DefaultQMKMacro"]));
            }
            set {
                this["DefaultQMKMacro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string DefaultQMKCaps {
            get {
                return ((string)(this["DefaultQMKCaps"]));
            }
            set {
                this["DefaultQMKCaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I")]
        public string DefaultQMKIndicator {
            get {
                return ((string)(this["DefaultQMKIndicator"]));
            }
            set {
                this["DefaultQMKIndicator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public string DefaultQMKQMK {
            get {
                return ((string)(this["DefaultQMKQMK"]));
            }
            set {
                this["DefaultQMKQMK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultTrackKeystroke {
            get {
                return ((bool)(this["DefaultTrackKeystroke"]));
            }
            set {
                this["DefaultTrackKeystroke"] = value;
            }
        }
    }
}
